<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Logout' => '',
    'Active' => '',
    'Address' => '',
    'Admin' => '',
    'All references' => '',
    'Application sent' => '',
    'Are you sure you want to delete this item?' => '',
    'Attachments ID' => '',
    'Author' => '',
    'Back' => '',
    'Categories' => '',
    'Categories Uzs' => '',
    'Complate' => '',
    'Complete' => '',
    'Content' => '',
    'Continued' => '',
    'Create Categories Uz' => '',
    'Create Message Uz' => '',
    'Create Reference' => '',
    'Create User' => '',
    'Created At' => '',
    'Created By' => '',
    'Date' => '',
    'Delete' => '',
    'Extension' => '',
    'Fill out the form to submit an application' => '',
    'Fullname' => '',
    'ID' => '',
    'Images' => '',
    'Login yoki Parol xato!' => '',
    'Message ID' => '',
    'Message Uzs' => '',
    'Message create' => '',
    'Name' => '',
    'Not found data' => '',
    'Not saved' => '',
    'Password' => '',
    'Path' => '',
    'Phone' => '',
    'Reference' => '',
    'Reference Message' => '',
    'References' => '',
    'References status' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Showing <strong>{begin}-{end}</strong> of <strong>{totalCount}</strong> items' => '',
    'Size' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Title' => '',
    'Type' => '',
    'Update' => '',
    'Update Categories Uz: {name}' => '',
    'Update Message Uz: {name}' => '',
    'Update Reference: {name}' => '',
    'Update User: {name}' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Username' => '',
    'Users' => '',
];
