<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute ID' => '',
    'Attribute name must contain latin word characters only.' => '',
    'Attribute {name} not found' => '',
    'Create' => '',
    'Default Option ID' => '',
    'Default Value' => '',
    'Default option Id' => '',
    'Description' => '',
    'Descriptions' => '',
    'Dynamic model data were no attributes.' => '',
    'Dynamic model data were not save due to validation error.' => '',
    'EAV Fields constructor' => '',
    'Entities constructor' => '',
    'Entity ID' => '',
    'Entity Model' => '',
    'Entity name' => '',
    'Fields constructor' => '',
    'Handler Class' => '',
    'ID Category' => '',
    'ID Model' => '',
    'Label' => '',
    'List' => '',
    'Locked' => '',
    'Name' => '',
    'Operations' => '',
    'Option ID' => '',
    'Options constructor' => '',
    'Order' => '',
    'Required' => '',
    'Route' => '',
    'Rules' => '',
    'Sort order' => '',
    'Store Type' => '',
    'Template default attributes' => '',
    'Template field button' => '',
    'Template settings' => '',
    'Template view' => '',
    'Type' => '',
    'Type ID' => '',
    'Type name must contain latin word characters only.' => '',
    'Types constructor' => '',
    'Value' => '',
    'Values constructor' => '',
    'Visible' => '',
];
