<?php

use yii\db\Migration;

/**
 * Class m200802_083719_insert_rows_to_hr_country_table
 */
class m200802_083719_insert_rows_to_hr_country_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->batchInsert('{{%hr_country}}', ['name', 'code'],
            [
                [
                    "O'zbekiston",
                    "UZ"
                ],
                [
                    "Turkiya",
                    "TR"
                ],
                [
                    "Xitoy",
                    "CN"
                ],
                [
                    "Germaniya",
                    "DE"
                ],
                [
                    "Italiya",
                    "IT"
                ],
                [
                    "Hindiston",
                    "IN"
                ],
                [
                    "Rossiya",
                    "RU"
                ],
                [
                    "Afg'oniston",
                    "AF"
                ],
                [
                    "Albaniya",
                    "AL"
                ],
                [
                    "Jazoir",
                    "DZ"
                ],
                [
                    "Amerika Samoasi",
                    "AS"
                ],
                [
                    "Andorra",
                    "AD"
                ],
                [
                    "Angola",
                    "AO"
                ],
                [
                    "Anguilla",
                    "AI"
                ],
                [
                    "Antarktida",
                    "AQ"
                ],
                [
                    "Antigua va Barbuda",
                    "AG"
                ],
                [
                    "Argentina",
                    "AR"
                ],
                [
                    "Armaniston",
                    "AM"
                ],
                [
                    "Aruba",
                    "AW"
                ],
                [
                    "Avstraliya",
                    "AU"
                ],
                [
                    "Avstriya",
                    "AT"
                ],
                [
                    "Ozarbayjon",
                    "AZ"
                ],
                [
                    "Bagam orollari",
                    "BS"
                ],
                [
                    "Bahrayn",
                    "BH"
                ],
                [
                    "Bangladesh",
                    "BD"
                ],
                [
                    "Barbados",
                    "BB"
                ],
                [
                    "Belarusiya",
                    "BY"
                ],
                [
                    "Belgiya",
                    "BE"
                ],
                [
                    "Beliz",
                    "BZ"
                ],
                [
                    "Benin",
                    "BJ"
                ],
                [
                    "Bermuda",
                    "BM"
                ],
                [
                    "Butan",
                    "BT"
                ],
                [
                    "Boliviya",
                    "BO"
                ],
                [
                    "Bosniya va Gertsegovina",
                    "BA"
                ],
                [
                    "Botsvana",
                    "BW"
                ],
                [
                    "Bouvet Island",
                    "BV"
                ],
                [
                    "Braziliya",
                    "BR"
                ],
                [
                    "Britaniya Hind okeanining hududi",
                    "IO"
                ],
                [
                    "Bruney",
                    "BN"
                ],
                [
                    "Bolgariya",
                    "BG"
                ],
                [
                    "Burkina-Faso",
                    "BF"
                ],
                [
                    "Burundi",
                    "BI"
                ],
                [
                    "Kambodja",
                    "KH"
                ],
                [
                    "Kamerun",
                    "CM"
                ],
                [
                    "Kanada",
                    "CA"
                ],
                [
                    "Kabo-Verde",
                    "CV"
                ],
                [
                    "Kayman orollari",
                    "KY"
                ],
                [
                    "Markaziy Afrika Respublikasi",
                    "CF"
                ],
                [
                    "Chad",
                    "TD"
                ],
                [
                    "Chili",
                    "CL"
                ],
                [
                    "Xitoy",
                    "CN"
                ],
                [
                    "Rojdestvo oroli",
                    "CX"
                ],
                [
                    "Kokos (Kiling) orollari",
                    "CC"
                ],
                [
                    "Kolumbiya",
                    "CO"
                ],
                [
                    "Komor",
                    "KM"
                ],
                [
                    "Kongo",
                    "CG"
                ],
                [
                    "Kuk orollari",
                    "CK"
                ],
                [
                    "Kosta-Rika",
                    "CR"
                ],
                [
                    "Xorvatiya",
                    "HR"
                ],
                [
                    "Kuba",
                    "CU"
                ],
                [
                    "Kipr",
                    "CY"
                ],
                [
                    "Chexiya",
                    "CZ"
                ],
                [
                    "Daniya",
                    "DK"
                ],
                [
                    "Jibuti",
                    "DJ"
                ],
                [
                    "Dominika",
                    "DM"
                ],
                [
                    "Dominik Respublikasi",
                    "DO"
                ],
                [
                    "Sharqiy Timor",
                    "TP"
                ],
                [
                    "Ekvador",
                    "EC"
                ],
                [
                    "Misr",
                    "EG"
                ],
                [
                    "Salvador",
                    "SV"
                ],
                [
                    "Ekvatorial Gvineya",
                    "GQ"
                ],
                [
                    "Eritreya",
                    "ER"
                ],
                [
                    "Estoniya",
                    "EE"
                ],
                [
                    "Efiopiya",
                    "ET"
                ],
                [
                    "Folklend orollari",
                    "FK"
                ],
                [
                    "Farer orollari",
                    "FO"
                ],
                [
                    "Fidji orollari",
                    "FJ"
                ],
                [
                    "Finlyandiya",
                    "FI"
                ],
                [
                    "Frantsiya",
                    "FR"
                ],
                [
                    "Frantsiya Gvianasi",
                    "GF"
                ],
                [
                    "Fransuz Polineziyasi",
                    "PF"
                ],
                [
                    "Frantsiyaning janubiy hududlari",
                    "TF"
                ],
                [
                    "Gabon",
                    "GA"
                ],
                [
                    "Gambiya",
                    "GM"
                ],
                [
                    "Gruziya",
                    "GE"
                ],
                [
                    "Gana",
                    "GH"
                ],
                [
                    "Gibraltar",
                    "GI"
                ],
                [
                    "Gretsiya",
                    "GR"
                ],
                [
                    "Grenlandiya",
                    "GL"
                ],
                [
                    "Grenada",
                    "GD"
                ],
                [
                    "Gvadelupa",
                    "GP"
                ],
                [
                    "Guam",
                    "GU"
                ],
                [
                    "Gvatemala",
                    "GT"
                ],
                [
                    "Gernsi",
                    "GG"
                ],
                [
                    "Gvineya",
                    "GN"
                ],
                [
                    "Gvineya-Bisau",
                    "GW"
                ],
                [
                    "Gayana",
                    "GY"
                ],
                [
                    "Gaiti",
                    "HT"
                ],
                [
                    "Xard oroli va Makdonald orollari",
                    "HM"
                ],
                [
                    "Muqaddas qarorgoh (Vatikan shtati)",
                    "VA"
                ],
                [
                    "Gonduras",
                    "HN"
                ],
                [
                    "Gonkong",
                    "HK"
                ],
                [
                    "Vengriya",
                    "HU"
                ],
                [
                    "Islandiya",
                    "IS"
                ],
                [
                    "Indoneziya",
                    "ID"
                ],
                [
                    "Eron",
                    "IR"
                ],
                [
                    "Iroq",
                    "IQ"
                ],
                [
                    "Irlandiya",
                    "IE"
                ],
                [
                    "Man oroli",
                    "IM"
                ],
                [
                    "Isroil",
                    "IL"
                ],
                [
                    "Ivory Coast",
                    "CI"
                ],
                [
                    "Yamayka",
                    "JM"
                ],
                [
                    "Yaponiya",
                    "JP"
                ],
                [
                    "Jersi",
                    "JE"
                ],
                [
                    "Iordaniya",
                    "JO"
                ],
                [
                    "Qozog'iston",
                    "KZ"
                ],
                [
                    "Keniya",
                    "KE"
                ],
                [
                    "Kiribati",
                    "KI"
                ],
                [
                    "Quvayt",
                    "KW"
                ],
                [
                    "Qirg'iziston",
                    "KG"
                ],
                [
                    "Laos",
                    "LA"
                ],
                [
                    "Latviya",
                    "LV"
                ],
                [
                    "Livan",
                    "LB"
                ],
                [
                    "Lesoto",
                    "LS"
                ],
                [
                    "Liberiya",
                    "LR"
                ],
                [
                    "Liviya Arab Jamahiriyasi",
                    "LY"
                ],
                [
                    "Lixtenshteyn",
                    "LI"
                ],
                [
                    "Litva",
                    "LT"
                ],
                [
                    "Lyuksemburg",
                    "LU"
                ],
                [
                    "Makao",
                    "MO"
                ],
                [
                    "Shimoliy Makedoniya",
                    "MK"
                ],
                [
                    "Madagaskar",
                    "MG"
                ],
                [
                    "Malavi",
                    "MW"
                ],
                [
                    "Malayziya",
                    "MY"
                ],
                [
                    "Maldiv orollari",
                    "MV"
                ],
                [
                    "Mali",
                    "ML"
                ],
                [
                    "Malta",
                    "MT"
                ],
                [
                    "Marshall orollari",
                    "MH"
                ],
                [
                    "Martinika",
                    "MQ"
                ],
                [
                    "Mavritaniya",
                    "MR"
                ],
                [
                    "Mavrikiy",
                    "MU"
                ],
                [
                    "Mayotte",
                    "YT"
                ],
                [
                    "Meksika",
                    "MX"
                ],
                [
                    "Mikroneziya, Federativ Shtatlari",
                    "FM"
                ],
                [
                    "Moldova",
                    "MD"
                ],
                [
                    "Monako",
                    "MC"
                ],
                [
                    "Mo'g'uliston",
                    "MN"
                ],
                [
                    "Chernogoriya",
                    "ME"
                ],
                [
                    "Montserrat",
                    "MS"
                ],
                [
                    "Marokash",
                    "MA"
                ],
                [
                    "Mozambik",
                    "MZ"
                ],
                [
                    "Myanma",
                    "MM"
                ],
                [
                    "Namibiya",
                    "NA"
                ],
                [
                    "Nauru",
                    "NR"
                ],
                [
                    "Nepal",
                    "NP"
                ],
                [
                    "Gollandiya",
                    "NL"
                ],
                [
                    "Niderlandiya Antil orollari",
                    "AN"
                ],
                [
                    "Yangi Kaledoniya",
                    "NC"
                ],
                [
                    "Yangi Zelandiya",
                    "NZ"
                ],
                [
                    "Nikaragua",
                    "NI"
                ],
                [
                    "Niger",
                    "NE"
                ],
                [
                    "Nigeriya",
                    "NG"
                ],
                [
                    "Niue",
                    "NU"
                ],
                [
                    "Norfolk oroli",
                    "NF"
                ],
                [
                    "Shimoliy Koreya",
                    "KP"
                ],
                [
                    "Shimoliy Irlandiya",
                    "GB"
                ],
                [
                    "Shimoliy Marian orollari",
                    "MP"
                ],
                [
                    "Norvegiya",
                    "YO'Q"
                ],
                [
                    "Ummon",
                    "OM"
                ],
                [
                    "Pokiston",
                    "PK"
                ],
                [
                    "Palau",
                    "PW"
                ],
                [
                    "Falastin",
                    "PS"
                ],
                [
                    "Panama",
                    "PA"
                ],
                [
                    "Papua-Yangi Gvineya",
                    "PG"
                ],
                [
                    "Paragvay",
                    "PY"
                ],
                [
                    "Peru",
                    "PE"
                ],
                [
                    "Filippin",
                    "PH"
                ],
                [
                    "Pitkairn",
                    "PN"
                ],
                [
                    "Polsha",
                    "PL"
                ],
                [
                    "Portugaliya",
                    "PT"
                ],
                [
                    "Puerto-Riko",
                    "PR"
                ],
                [
                    "Qatar",
                    "QA"
                ],
                [
                    "Qaytish",
                    "RE"
                ],
                [
                    "Ruminiya",
                    "RO"
                ],
                [
                    "Ruanda",
                    "RW"
                ],
                [
                    "Muqaddas Yelena",
                    "SH"
                ],
                [
                    "Sent-Kits va Nevis",
                    "KN"
                ],
                [
                    "Sent-Lusiya",
                    "LC"
                ],
                [
                    "Sent-Per va Mikelon",
                    "PM"
                ],
                [
                    "Sent-Vinsent va Grenadinlar",
                    "VC"
                ],
                [
                    "Samoa",
                    "WS"
                ],
                [
                    "San-Marino",
                    "SM"
                ],
                [
                    "San-Tome va Prinsip",
                    "ST"
                ],
                [
                    "Saudiya Arabistoni",
                    "SA"
                ],
                [
                    "Senegal",
                    "SN"
                ],
                [
                    "Serbiya",
                    "RS"
                ],
                [
                    "Seyshel orollari",
                    "SC"
                ],
                [
                    "Syerra-Leone",
                    "SL"
                ],
                [
                    "Singapur",
                    "SG"
                ],
                [
                    "Slovakiya",
                    "SK"
                ],
                [
                    "Sloveniya",
                    "SI"
                ],
                [
                    "Solomon orollari",
                    "SB"
                ],
                [
                    "Somali",
                    "SO"
                ],
                [
                    "Janubiy Afrika",
                    "ZA"
                ],
                [
                    "Janubiy Jorjiya va Janubiy sendvich orollari",
                    "GS"
                ],
                [
                    "Janubiy Koreya",
                    "KR"
                ],
                [
                    "Janubiy Sudan",
                    "SS"
                ],
                [
                    "Ispaniya",
                    "ES"
                ],
                [
                    "Shri-Lanka",
                    "LK"
                ],
                [
                    "Sudan",
                    "SD"
                ],
                [
                    "Surinam",
                    "SR"
                ],
                [
                    "Svalbard va Yan Mayen",
                    "SJ"
                ],
                [
                    "Svazilend",
                    "SZ"
                ],
                [
                    "Shvetsiya",
                    "SE"
                ],
                [
                    "Shveytsariya",
                    "CH"
                ],
                [
                    "Suriya",
                    "SY"
                ],
                [
                    "Tojikiston",
                    "TJ"
                ],
                [
                    "Tanzaniya",
                    "TZ"
                ],
                [
                    "Tailand",
                    "TH"
                ],
                [
                    "Kongo Demokratik Respublikasi",
                    "CD"
                ],
                [
                    "Timor-Leste",
                    "TL"
                ],
                [
                    "Togo",
                    "TG"
                ],
                [
                    "Tokelau",
                    "TK"
                ],
                [
                    "Tonga",
                    "TO"
                ],
                [
                    "Trinidad va Tobago",
                    "TT"
                ],
                [
                    "Tunis",
                    "TN"
                ],
                [
                    "Turkmaniston",
                    "TM"
                ],
                [
                    "Turk va Kaykos orollari",
                    "TC"
                ],
                [
                    "Tuvalu",
                    "TV"
                ],
                [
                    "Uganda",
                    "UG"
                ],
                [
                    "Ukraina",
                    "UA"
                ],
                [
                    "Birlashgan Arab Amirliklari",
                    "AE"
                ],
                [
                    "Buyuk Britaniya",
                    "GB"
                ],
                [
                    "Amerika Qo'shma Shtatlari",
                    "US"
                ],
                [
                    "AQShning kichik tashqi orollari",
                    "UM"
                ],
                [
                    "Urugvay",
                    "UY"
                ],
                [
                    "Vanuatu",
                    "VU"
                ],
                [
                    "Venesuela",
                    "VE"
                ],
                [
                    "Vetnam",
                    "VN"
                ],
                [
                    "Virgin orollari, Britaniya",
                    "VG"
                ],
                [
                    "Virjiniya orollari, AQSh",
                    "VI"
                ],
                [
                    "Uollis va Futuna",
                    "WF"
                ],
                [
                    "G'arbiy Sahro",
                    "EH"
                ],
                [
                    "Yaman",
                    "YE"
                ],
                [
                    "Yugoslaviya",
                    "YU"
                ],
                [
                    "Zambiya",
                    "ZM"
                ],
                [
                    "Zimbabve",
                    "ZW"
                ]
            ]
        );
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m200802_083719_insert_rows_to_hr_country_table cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m200802_083719_insert_rows_to_hr_country_table cannot be reverted.\n";

        return false;
    }
    */
}
