<?php

namespace app\modules\settings\models;

use Yii;

/**
 * This is the model class for table "currency".
 *
 * @property int $id
 * @property double $usd
 * @property string $start_date
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int $created_by
 * @property string $add_info
 */
class Currency extends \app\modules\toquv\models\BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'currency';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['usd'], 'required'],
            [['usd'], 'number'],
            [['start_date'], 'safe'],
            [['status', 'created_at', 'updated_at', 'created_by'], 'integer'],
            [['add_info'], 'string'],
        ];
    }

    /**
     * @param null $date
     * @return mixed
     */
    public static function getCurrency($date = null)
    {
       $return = [];
       if ($date) {
           $return = self::find()->where([['<=','start_date', date('Y-m-d', strtotime($date))], ['=', 'status', self::STATUS_ACTIVE]])->orderBy(['start_date'=>SORT_DESC])->limit(1)->asArray()->one();
       } else {
           $return = self::find()->where(['=', 'status', self::STATUS_ACTIVE])->orderBy(['start_date'=>SORT_DESC])->limit(1)->asArray()->one();
       }

       return $return['usd'];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'usd' => Yii::t('app', 'Usd'),
            'start_date' => Yii::t('app', 'Start Date'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'created_by' => Yii::t('app', 'Created By'),
            'add_info' => Yii::t('app', 'Add Info'),
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_by = Yii::$app->user->getId();
            $this->created_at = $time = time();
            $this->start_date = date("Y-m-d",$time);
            $this->updated_at = $time;
        }else{
            $this->updated_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
