<?php

use yii\db\Migration;

/**
 * Class m190913_181946_change_foreign_key_model_table
 */
class m190913_181946_change_foreign_key_model_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_rel_attach-model_var_id',
            'model_var_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_rel_attach-model_var_id',
            'model_var_rel_attach',
            'model_var_id',
            'models_variations',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_stone_id
        $this->dropForeignKey(
            'fk-model_var_stone_rel_attach-model_var_stone_id',
            'model_var_stone_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_stone_rel_attach-model_var_stone_id',
            'model_var_stone_rel_attach',
            'model_var_stone_id',
            'model_var_stone',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_print_id
        $this->dropForeignKey(
            'fk-model_var_print_rel_attach-model_var_print_id',
            'model_var_print_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_print_rel_attach-model_var_print_id',
            'model_var_print_rel_attach',
            'model_var_print_id',
            'model_var_prints',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_baski_id
        $this->dropForeignKey(
            'fk-model_var_baski_rel_attach-model_var_baski_id',
            'model_var_baski_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_baski_rel_attach-model_var_baski_id',
            'model_var_baski_rel_attach',
            'model_var_baski_id',
            'model_var_baski',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-models_variation_colors-model_var_id',
            'models_variation_colors'
        );
        $this->addForeignKey(
            'fk-models_variation_colors-model_var_id',
            'models_variation_colors',
            'model_var_id',
            'models_variations',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_prints-model_var_id',
            'model_var_prints'
        );
        $this->addForeignKey(
            'fk-model_var_prints-model_var_id',
            'model_var_prints',
            'model_var_id',
            'models_variations',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_stone-model_var_id',
            'model_var_stone'
        );
        $this->addForeignKey(
            'fk-model_var_stone-model_var_id',
            'model_var_stone',
            'model_var_id',
            'models_variations',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_baski-model_var_id',
            'model_var_baski'
        );
        $this->addForeignKey(
            'fk-model_var_baski-model_var_id',
            'model_var_baski',
            'model_var_id',
            'models_variations',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-models_variations-model_list_id',
            'models_variations'
        );
        $this->addForeignKey(
            'fk-models_variations-model_list_id',
            'models_variations',
            'model_list_id',
            'models_list',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-model_rel_attach-model_list_id',
            'model_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_rel_attach-model_list_id',
            'model_rel_attach',
            'model_list_id',
            'models_list',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-models_raw_materials-model_list_id',
            'models_raw_materials'
        );
        $this->addForeignKey(
            'fk-models_raw_materials-model_list_id',
            'models_raw_materials',
            'model_list_id',
            'models_list',
            'id',
            'CASCADE',
            'CASCADE'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-models_acs-model_list_id',
            'models_acs'
        );
        $this->addForeignKey(
            'fk-models_acs-model_list_id',
            'models_acs',
            'model_list_id',
            'models_list',
            'id',
            'CASCADE',
            'CASCADE'
        );
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_rel_attach-model_var_id',
            'model_var_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_rel_attach-model_var_id',
            'model_var_rel_attach',
            'model_var_id',
            'models_variations',
            'id'
        );
        //model_var_stone_id
        $this->dropForeignKey(
            'fk-model_var_stone_rel_attach-model_var_stone_id',
            'model_var_stone_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_stone_rel_attach-model_var_stone_id',
            'model_var_stone_rel_attach',
            'model_var_stone_id',
            'model_var_stone',
            'id'
        );
        //model_var_print_id
        $this->dropForeignKey(
            'fk-model_var_print_rel_attach-model_var_print_id',
            'model_var_print_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_print_rel_attach-model_var_print_id',
            'model_var_print_rel_attach',
            'model_var_print_id',
            'model_var_prints',
            'id'
        );
        //model_var_baski_id
        $this->dropForeignKey(
            'fk-model_var_baski_rel_attach-model_var_baski_id',
            'model_var_baski_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_var_baski_rel_attach-model_var_baski_id',
            'model_var_baski_rel_attach',
            'model_var_baski_id',
            'model_var_baski',
            'id'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-models_variation_colors-model_var_id',
            'models_variation_colors'
        );
        $this->addForeignKey(
            'fk-models_variation_colors-model_var_id',
            'models_variation_colors',
            'model_var_id',
            'models_variations',
            'id'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_prints-model_var_id',
            'model_var_prints'
        );
        $this->addForeignKey(
            'fk-model_var_prints-model_var_id',
            'model_var_prints',
            'model_var_id',
            'models_variations',
            'id'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_stone-model_var_id',
            'model_var_stone'
        );
        $this->addForeignKey(
            'fk-model_var_stone-model_var_id',
            'model_var_stone',
            'model_var_id',
            'models_variations',
            'id'
        );
        //model_var_id
        $this->dropForeignKey(
            'fk-model_var_baski-model_var_id',
            'model_var_baski'
        );
        $this->addForeignKey(
            'fk-model_var_baski-model_var_id',
            'model_var_baski',
            'model_var_id',
            'models_variations',
            'id'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-models_variations-model_list_id',
            'models_variations'
        );
        $this->addForeignKey(
            'fk-models_variations-model_list_id',
            'models_variations',
            'model_list_id',
            'models_list',
            'id'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-model_rel_attach-model_list_id',
            'model_rel_attach'
        );
        $this->addForeignKey(
            'fk-model_rel_attach-model_list_id',
            'model_rel_attach',
            'model_list_id',
            'models_list',
            'id'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-models_raw_materials-model_list_id',
            'models_raw_materials'
        );
        $this->addForeignKey(
            'fk-models_raw_materials-model_list_id',
            'models_raw_materials',
            'model_list_id',
            'models_list',
            'id'
        );
        //model_list_id
        $this->dropForeignKey(
            'fk-models_acs-model_list_id',
            'models_acs'
        );
        $this->addForeignKey(
            'fk-models_acs-model_list_id',
            'models_acs',
            'model_list_id',
            'models_list',
            'id'
        );
    }
}
