<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Faol',
    'Address' => 'Manzil',
    'Admin' => 'Admin',
    'Application sent' => 'Murojat yuborildi',
    'Are you sure you want to delete this item?' => 'Haqiqatan ham ushbu narsani o\'chirishni xohlaysizmi?',
    'Attachments ID' => 'Fayllar',
    'Author' => 'Muallif',
    'Back' => 'Orqaga qaytish',
    'Categories' => 'Bo\'limlar',
    'Categories Uzs' => 'Bo\'limlar (uzbek)',
    'Complate' => 'Yakunlangan',
    'Complete' => 'Yakunlangan',
    'Content' => 'Matn',
    'Continued' => 'Ko\'rib chiqilmoqda',
    'Create Categories Uz' => 'Bo\'lim qo\'shish (uzbek)',
    'Create Message Uz' => 'Ma\'lumot qo\'shish (uzbek)',
    'Create Reference' => 'Murojat yaratish',
    'Create User' => 'Foydalanuvchi qo\'shish',
    'Created At' => 'Yaratilgan vaqti',
    'Created By' => 'Kim tomonidan yaratildi',
    'Date' => 'Vaqt',
    'Delete' => 'O\'chirish',
    'Extension' => 'Kengaytma',
    'Fill out the form to submit an application' => 'Arizani topshirish uchun anketani to\'ldiring',
    'Fullname' => 'To\'liq ism sharif',
    'ID' => 'Id',
    'Images' => 'Rasmlar',
    'Login yoki Parol xato!' => 'Login yoki Parol xato',
    'Message ID' => 'Ma\'lumot',
    'Message Uzs' => 'Ma\'lumot (uzbek)',
    'Message create' => 'Ma\'lumot qo\'shish',
    'Name' => 'Nomi',
    'Not found data' => 'Ma\'lumot topilmadi',
    'Not saved' => 'Saqlanmadi',
    'Password' => 'Parol',
    'Path' => 'Yo\'li',
    'Phone' => 'Telefon nomer',
    'Reference' => 'Murojat',
    'Reference Message' => 'Murojat uchun matn',
    'References' => 'Murojatlar',
    'Reset' => 'Yangilash',
    'Save' => 'Saqlash',
    'Search' => 'Qidirish',
    'Showing <strong>{begin}-{end}</strong> of <strong>{totalCount}</strong> items' => 'Namoyish etilyabdi <strong>{begin}-{end}</strong>. Jami <strong>{totalCount}</strong> ta',
    'Size' => 'O\'lcham',
    'Status' => 'Xolati',
    'The requested page does not exist.' => 'So\'ralgan sahifa mavjud emas',
    'Title' => 'Sarlavha',
    'Type' => 'Tipi',
    'Update' => 'Yangilash',
    'Update Categories Uz: {name}' => 'Bo\'limlarni yangilash (uzbek) {name}',
    'Update Message Uz: {name}' => 'Ma\'lumotni yangilash (uzbek) {name}',
    'Update Reference: {name}' => 'Murojatni yangilash {name}',
    'Update User: {name}' => 'Foydalanuvchini yangilash (uzbek) {name}',
    'Updated At' => 'Yangilangan vaqti',
    'Updated By' => 'Kim tomonidan yangilandi',
    'Username' => 'Foydalanuvchi logini',
    'Users' => 'Foydalanuvchilar',
    ' Logout' => '',
    'All references' => 'Barcha murojatlar',
    'References status' => 'Murojatlar holati',
];
